version: "3"

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - ./src:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=poll_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e
